Cleanup of white-space on freshen_repos

diff --git a/bin/freshen_repos b/bin/freshen_repos
--- a/bin/freshen_repos
+++ b/bin/freshen_repos
@@ -3,80 +3,75 @@
 
 
 gpa() {
-	GIT_CURRENT=`git branch | grep \* | awk '{print $2}'`
-	GIT_CURRENTDIR=`pwd`
-	GIT_TOPDIR=`git rev-parse --show-toplevel`
-	cd $GIT_TOPDIR
+    GIT_CURRENT=`git branch | grep \* | awk '{print $2}'`
+    GIT_CURRENTDIR=`pwd`
+    GIT_TOPDIR=`git rev-parse --show-toplevel`
+    cd $GIT_TOPDIR
+    for x in `git branch | tr -d \* `; do
+        git checkout $x && git pull
+    done
+    git checkout $GIT_CURRENT
+    cd $GIT_CURRENTDIR
+}
 
-	for x in `git branch | tr -d \* `
-		do git checkout $x && git pull
-		done
-	git checkout $GIT_CURRENT
-	cd $GIT_CURRENTDIR
-	}
 freshen_repos() {
-	AMIGITREPO=`git status 2>&1 > /dev/null`
-	RC=$?
-	if [ $RC = 0 ]
-	then
-		echo "In a git repo, we will use gpa instead"
-		gpa
-		exit
-	fi
-	for repo in *
-		do
-		echo "=========================="
-		echo "\n\n ======== ${repo} ========= "
-		echo " "
-		if [ -d $repo ]
-		then
-		cd $repo
-			gpa
-			cd ../
-		else
-			echo " ${repo} Not a dir, so can't be a repo"
-		echo " "
-		fi
-		done
-	}
+    AMIGITREPO=`git status 2>&1 > /dev/null`
+    RC=$?
+    if [ $RC = 0 ]; then
+        echo "In a git repo, we will use gpa instead"
+        gpa
+        exit
+    fi
+    for repo in *; do
+        echo "=========================="
+        echo "\n\n ======== ${repo} ========= "
+        echo " "
+        if [ -d $repo ]; then
+            cd $repo
+            gpa
+            cd ../
+        else
+            echo " ${repo} Not a dir, so can't be a repo"
+            echo " "
+        fi
+    done
+}
+
 push_repos() {
-	AMIGITREPO=`git status 2>&1 > /dev/null`
-	RC=$?
-	if [ $RC = 0 ]
-	then
-		echo "In a git repo already"
-		git push
-		exit
-	fi
-	for repo in *
-		do
-		echo " ======== ${repo} ========= "
-		echo " "
-		if [ -d $repo ]
-		then
-		cd $repo
-			git push
-			cd ../
-		else
-			echo " ${repo} Not a dir, so can't be a repo"
-		echo " "
-		fi
-		done
-	}
+    AMIGITREPO=`git status 2>&1 > /dev/null`
+    RC=$?
+    if [ $RC = 0 ]; then
+        echo "In a git repo already"
+        git push
+        exit
+    fi
+    for repo in *; do
+        echo " ======== ${repo} ========= "
+        echo " "
+        if [ -d $repo ]; then
+            cd $repo
+            git push
+            cd ../
+        else
+            echo " ${repo} Not a dir, so can't be a repo"
+            echo " "
+        fi
+    done
+}
 
 
 base="$(basename "$0")"
 case $base in
-	freshen_repos)
-		freshen_repos
-	;;
-	gpa)
-		gpa
-	;;
-	pushall)
-		push_repos
-	;;
-	*)
-		echo "Catchall, try again"
-	;;
+    freshen_repos)
+        freshen_repos
+        ;;
+    gpa)
+        gpa
+        ;;
+    pushall)
+        push_repos
+        ;;
+    *)
+        echo "Catchall, try again"
+        ;;
 esac
